name: Build Electron App on Windows

# 触发条件：推送、Pull Request 或手动触发时执行
on: 
  [push, pull_request, workflow_dispatch]

jobs:
  build-on-windows:
    runs-on: windows-latest  # 使用 Windows runner
    steps:
      # Step 1: 检出代码
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # 根据需求设置为 '14.x' 或 '20.x'

      # Step 3: 使用 Chocolatey 安装依赖（Python, vcredist-all, make）
      - name: Install Dependencies via Chocolatey
        run: |
          choco install python310 make -y
      # Step 4: 安装项目依赖
      - name: Install Project Dependencies
        run: |
          make i
      # Step 5: 构建应用
      - name: Build Application
        run: make build
      
      - name: Build
        run: ./node_modules/.bin/gulp win-arm64

      # Step 7: 上传构建产物（可选）
      - name: Upload Windows ARM64 Build
        uses: actions/upload-artifact@v3
        with:
          name: win-arm64-build
          path: 'build/Kodo Browser-win-arm64/' # 确保路径正确
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/kodo-browser-win32-x64-${{ steps.vars.outputs.tag }}.zip
          asset_name: kodo-browser-win32-x64-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip

