on: [push, pull_request]
name: Test Build
jobs:
  build-on-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: install wine
        # https://github.com/actions/virtual-environments/issues/4589
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
          sudo add-apt-repository 'deb [arch=amd64] https://mirror.mxe.cc/repos/apt focal main'
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt -qq update
          sudo apt install -yqq --allow-downgrades libgd3/focal libpcre2-8-0/focal libpcre2-16-0/focal libpcre2-32-0/focal libpcre2-posix2/focal
          sudo apt purge -yqq libmono* mono* php* libgdiplus libpcre2-posix3
          sudo apt install -y wine32 wine64
      - name: test
        run: make i
      - name: build
        run: make build
      - name: Build
        run: ./node_modules/.bin/gulp win-arm64
      # Step 7: 上传构建产物（可选）
      - name: Upload Windows ARM64 Build
        uses: actions/upload-artifact@v3
        with:
          name: win-arm64-build
          path: dist/win-arm64/  # 确保路径正确
